version: '3.3'

services:
    mongo:
        image: mongo:4
        volumes:
            - data:/data/db
        networks:
            - internal

    redis:
        image: redis:alpine
        networks:
            - internal
